api/urls.py
from django.urls import path, include
from .views import ProductoList, ProductoDetalle

urlpatterns = [
    path('v1/productos/',ProductoList.as_view(),name='producto_list'),
    path('v1/productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_detalle'),
]

compras/urls.py
"""Compras URLs."""

# Django
from django.urls import path

# View
# from compras import views

from .views import index, compras, ComprasView, CompraDetDelete

urlpatterns = [

    path(
        route='',
        view=ComprasView.as_view(),
        name='compras_list'
    ),
    path('new/',compras, name="compras_new"),
    path('edit/<int:compra_id>',compras, name="compras_edit"),    
    path('compras/<int:compra_id>/delete/<int:pk>',CompraDetDelete.as_view(), name="compras_del"),

]

ferreteria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views

urlpatterns = [    
    path('admin/', admin.site.urls),
    path('',views.welcome, name="feed"),
    path('compras/', include(('compras.urls', 'compras'), namespace='compras')),
    path('clientes/', include(('clientes.urls', 'clientes'), namespace='clientes')),
    path('productos/', include(('productos.urls', 'productos'), namespace='productos')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('ventas/',include(('ventas.urls','ventas'),namespace='ventas')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

compras/models.py
from django.db import models
from django.contrib.auth.models import User
from productos.models import Producto
from decimal import *
from django.db.models import Sum
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete


# Create your models here.

class CompraEncabezado(models.Model):    
    #monto = models.DecimalField(max_digits=8, decimal_places=2)
    estado = models.BooleanField(default=True)
    fechaCreacion = models.DateTimeField(auto_now_add=True)
    fechaModificacion = models.DateTimeField(auto_now=True)
    idOrdenCompra = models.IntegerField(unique=True)
    usuario = models.ForeignKey(User,on_delete=models.CASCADE)
    observaciones = models.TextField(blank=True, null=True)
    sub_total=models.DecimalField(max_digits=8, decimal_places=2, default=0)
    total=models.DecimalField(max_digits=8, decimal_places=2)


    def __str__(self):
        return '{}'.format(self.observaciones)

    def save(self):
        self.observaciones = self.observaciones.upper()
        self.total = self.sub_total 
        super(CompraEncabezado,self).save()

    class Meta:
        verbose_name_plural = "Encabezado Compras"
        verbose_name="Encabezado Compra"


class CompraDetalle(models.Model):
    idCompra = models.ForeignKey(CompraEncabezado, on_delete=models.CASCADE)
    cantidad = models.BigIntegerField(default=1)    
    costo = models.DecimalField(max_digits=8, decimal_places=2)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    precio_prv=models.DecimalField(max_digits=8, decimal_places=2)
    sub_total=models.DecimalField(max_digits=8, decimal_places=2, default=0)    
    total=models.DecimalField(max_digits=8, decimal_places=2)
    

    def __str__(self):
        return '{}'.format(self.producto)

    def save(self):
        self.sub_total = Decimal(Decimal(int(self.cantidad)) * Decimal(self.precio_prv))
        self.total = self.sub_total
        super(CompraDetalle, self).save()
    
    class Mega:
        verbose_name_plural = "Detalles Compras"
        verbose_name="Detalle Compra"



@receiver(post_delete, sender=CompraDetalle)
def detalle_compra_borrar(sender,instance, **kwargs):
    id_producto = instance.producto.id
    id_compra = instance.compra.id

    enc = CompraEncabezado.objects.filter(pk=id_compra).first()
    if enc:
        sub_total = CompraDetalle.objects.filter(idCompra=id_compra).aggregate(Sum('sub_total'))
        #descuento = CompraDetalle.objects.filter(compra=id_compra).aggregate(Sum('descuento'))
        enc.sub_total=sub_total['sub_total__sum']
        # enc.descuento=descuento['descuento__sum']
        enc.save()
    
    prod=Producto.objects.filter(pk=id_producto).first()
    if prod:
        cantidad = int(prod.existencia) - int(instance.cantidad)
        prod.existencia = cantidad
        prod.save()


@receiver(post_save, sender=CompraDetalle)
def detalle_compra_guardar(sender,instance,**kwargs):
    id_producto = instance.producto.id
    # fecha_compra=instance.compra.fecha_compra
    print(id_producto)
    prod=Producto.objects.filter(pk=id_producto).first()
    if prod:
        cantidad = int(prod.existencia) + int(instance.cantidad)
        prod.existencia = cantidad
        #prod.ultima_compra=fecha_compra
        prod.save()

compras/forms.py
from django import forms
from compras.models import CompraEncabezado


class ComprasEncForm(forms.ModelForm):
    fecha_compra = forms.DateInput()

    class Meta:
        model = CompraEncabezado
        fields = ['idOrdenCompra','observaciones','sub_total',
        'total']
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

        self.fields['sub_total'].widget.attrs['readonly'] = True
        self.fields['total'].widget.attrs['readonly'] = True




compras/views.py
"""Compras views."""

from django.shortcuts import render,redirect
from django.views import generic
from django.urls import reverse_lazy
import datetime
from django.http import HttpResponse, JsonResponse

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse
import json
from django.db.models import Sum

from compras.models import CompraDetalle, CompraEncabezado
from compras.forms import ComprasEncForm
# from bases.views import SinPrivilegios
from productos.models import Producto


def index(request):
    return render(request,'compras/compras.html')


class ComprasView(generic.ListView):
    model = CompraEncabezado
    template_name = "compras/compras_list.html"
    context_object_name = "obj"
    # permission_required="cmp.view_comprasenc"



@login_required(login_url='/users/login/')

def compras(request,compra_id=None):
    template_name = 'compras/compras.html'
    prod = Producto.objects.filter(estado=True)
    form_compras = {}
    contexto = {}

    if request.method=='GET':
        form_compras = ComprasEncForm()
        enc = CompraEncabezado.objects.filter(pk=compra_id).first()

        if enc:
            det = CompraDetalle.objects.filter(idCompra = enc)
            e = {
                'observaciones': enc.observaciones,
                'idOrdenCompra': enc.idOrdenCompra,
                'sub_total': enc.sub_total,
                'total': enc.total
            }
            form_compras = ComprasEncForm(e)
        else:
            det = None
                
        contexto = {'productos':prod,'encabezado':enc,'detalle':det,'form_enc':form_compras}
        print(prod)
        print(enc)

    if request.method=='POST':
        observaciones = request.POST.get("observaciones")
        idOrdenCompra = request.POST.get("idOrdenCompra")

        sub_total = 0
        total = 0

        if not compra_id:
            enc = CompraEncabezado(
                observaciones = observaciones,
                idOrdenCompra = idOrdenCompra,
                usuario = request.user
            )
            if enc:
                enc.save()
                compra_id = enc.id
        else:
            enc = CompraEncabezado.objects.filter(pk=compra_id).first()
            if enc:
                enc.observaciones = observaciones
                enc.idOrdenCompra = idOrdenCompra
                enc.save()

        if not compra_id:
            return redirect("compras:feed")


        producto = request.POST.get('id_id_producto')        
        cantidad = request.POST.get('id_cantidad_detalle')
        costo = request.POST.get('id_precio_detalle')
        sub_total_detalle = request.POST.get("id_sub_total_detalle")
        # descuento_detalle  = request.POST.get("id_descuento_detalle")
        total_detalle  = request.POST.get("id_total_detalle")
        


        prod = Producto.objects.get(pk=producto)        

        det = CompraDetalle(
            idCompra = enc,
            producto = prod,
            cantidad = cantidad,
            precio_prv=costo,            
            costo = 0
        )

        if det:
            det.save()

            sub_total=CompraDetalle.objects.filter(idCompra=compra_id).aggregate(Sum('sub_total'))
            #descuento=CompraDetalle.objects.filter(idCompra=compra_id).aggregate(Sum('descuento'))
            enc.sub_total = sub_total["sub_total__sum"]
            #enc.descuento=descuento["descuento__sum"]
            enc.save()

            return redirect('compras:compras_edit',compra_id=compra_id)

    
    return render(request,template_name,contexto)



class CompraDetDelete(generic.DeleteView):
    model = CompraDetalle
    template_name = "compras/compras_det_del.html"
    context_object_name = 'obj'
    
    def get_success_url(self):
          compra_id=self.kwargs['idCompra']
          return reverse_lazy('compras:compras_edit', kwargs={'idCompra': compra_id})

templates/compras/compras_det_del.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <form role="form" action="{% url 'compras:compras_del' obj.idCompra.id obj.pk %}" method="post"  class="form-inline">
            <div class="col-xl-12 col-md-12 mb-12">
                <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Eliminar Detalle
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            ¿Eliminar {{ obj.producto }} de compra número  <b>{{ obj.idCompra.id}} </b> ?
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Si, Eliminar</button>
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div> 

templates/compras/compras_list.html
{% extends 'base.html' %}
{% load static %}


{% block head_content %}
    <title>Lista de compras</title>
{% endblock head_content %}


{% block container %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de compras</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones:</div>
          <a class="dropdown-item" href="{% url 'compras:compras_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
          <a class="dropdown-item" href="" target="reportes"><i class="fas fa-print"></i> Listado</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
      <div class="alert alert-info">No hay compras</div>
      {% endif %}
      <table class="table table-striped table-hover dt-responsive nowrap" style="width:100%">
        <thead>
          <th>Id</th>        
          <th>Fecha</th>
          <th>Observación</th>
          <th>No. Orden compra</th>          
          <th>Sub Total</th>          
          <th>Total</th>
          <th>Estado</th>
          <th class="all">Acciones</th>
        </thead>
        <tbody>
          {% for item in obj%}
          <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.fechaCreacion }}</td>
            <td>{{item.observaciones}}</td>
            <td>{{item.idOrdenCompra}}</td>            
            <td>{{ item.sub_total }}</td>
            <td>{{ item.total }}</td>                        
            <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
            <td>
              <a class="btn btn-warning btn-circle" href="{% url 'compras:compras_edit' item.id %}"><i class="far fa-edit"></i></a>
              
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
// Call the dataTables jQuery plugin
$(document).ready(function() {
  $('.table').DataTable({
    "language": {
      "sProcessing": "Procesando...",
      "sLengthMenu": "Mostrar _MENU_ registros",
      "sZeroRecords": "No se encontraron resultados",
      "sEmptyTable": "Ningún dato disponible en esta tabla",
      "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
      "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
      "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
      "sInfoPostFix": "",
      "sSearch": "Buscar:",
      "sUrl": "",
      "sInfoThousands": ",",
      "sLoadingRecords": "Cargando...",
      "oPaginate": {
          "sFirst": "<span class='fa fa-angle-double-left'></span>",
          "sLast": "<span class='fa fa-angle-double-right'></span>",
          "sNext": "<span class='fa fa-angle-right'></span>",
          "sPrevious": "<span class='fa fa-angle-left'></span>"
      },
      "oAria": {
          "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
          "sSortDescending": ": Activar para ordenar la columna de manera descendente"
      }
    }
  });
});
</script>
{% endblock %}