api/urls.py
from django.urls import path, include
from .views import ProductoList, ProductoDetalle

urlpatterns = [
    path('v1/productos/',ProductoList.as_view(),name='producto_list'),
    path('v1/productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_detalle'),
]

ferreteria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views

urlpatterns = [    
    path('admin/', admin.site.urls),
    path('',views.welcome, name="feed"),
    path('compras/', include(('compras.urls', 'compras'), namespace='compras')),
    path('clientes/', include(('clientes.urls', 'clientes'), namespace='clientes')),
    path('productos/', include(('productos.urls', 'productos'), namespace='productos')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('ventas/',include(('ventas.urls','ventas'),namespace='ventas')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productos/urls.py
"""
URLS para productos
"""

from django.urls import path
from productos import views

urlpatterns = [
    path(
        route = '',
        view = views.ProductsDetailView.as_view(),
        name='detail'
    ),
    path(
        route = 'nuevo',
        view = views.ProductsCreateView.as_view(),
        name='new'
    ),
    path(
        route = 'editar/<int:pk>',
        view = views.ProductEditView.as_view(),
        name = 'edit'
    )
]

productos/models.py
from django.db import models

# Create your models here.
class Producto(models.Model):
    descripcion = models.CharField(max_length=300, blank=False)
    precio = models.DecimalField(max_digits=8, decimal_places=2)
    costo = models.DecimalField(max_digits=8, decimal_places=2)
    existencia = models.IntegerField()
    estado = models.BooleanField(default=True)
    fechaCreacion = models.DateTimeField(auto_now_add=True)
    fechaModificacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.descripcion

productos/forms.py
from django import forms
from productos.models import Producto


class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        #fields = '__all__'
        fields = ['descripcion','costo','precio','existencia']

productos/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from productos.models import Producto
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView

from productos.forms import ProductoForm
# Create your views here.



class ProductsDetailView(LoginRequiredMixin, ListView):
    """Return products detail."""

    template_name = 'productos/detail.html'
    model = Producto
    ordering = ('-fechaCreacion',)
    context_object_name = 'productos'



class ProductsCreateView(LoginRequiredMixin,CreateView):
    """ Crea un nuevo producto """
    template_name = "productos/new.html"
    form_class = ProductoForm
    success_url = reverse_lazy('productos:detail')

class ProductEditView(LoginRequiredMixin,UpdateView):
    template_name = "productos/editar.html"
    model = Producto
    success_url = reverse_lazy('productos:detail')
    fields = ['precio','costo','existencia','estado']

templates/productos/detail.html
{% extends "base.html" %}

{% block head_content %}
    <title>Productos</title>
{% endblock%}

{% block container %}

<div class="container">
    <div class="row">
      <div class="col-12">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Descripcion</th>
              <th scope="col">Precio</th>
              <th scope="col">Costo</th>
              <th scope="col">Existencias</th>
              <th scope="col">Estado</th>
              <th scope="col">Acciones</th>
            </tr>
          </thead>
          <tbody>
            {% for prod in productos %}  
      

            <tr>  
                <td>{{ prod.id }}</td>  
                <td>{{ prod.descripcion }}</td>  
                <td>{{ prod.precio }}</td>  
                <td>{{ prod.costo }}</td>  
                <td>{{ prod.existencia }}</td>  
                  
                {% csrf_token %}
                <td class="center"><input type="checkbox" disabled name="checkbox"  {%if prod.estado %}checked{% endif %}/></td>
                
                <td>                     
                   <a href="{% url "productos:edit" prod.id %}" class="btn btn-success"><i class="fas fa-edit"></i></a>                   
                  </td>
            </tr>  
            {% endfor %}  
          </tbody>
        </table>
        <br>
        <br>
        <a href="{% url "productos:new" %}" class="btn btn-primary"><i class="fas fa-plus-circle"></i> Agregar nuevo</a>
      </div>
    </div>
  </div>

    

{% endblock %}

templates/productos/editar.html
{% extends 'base.html' %}


{% block head_content %}
    <title>Editar</title>
{% endblock head_content %}


{% block container %}

<div class="container">
    <form method="POST">
        {% csrf_token %}
        <div class="form-row">
        <div class="form-group col-md-4">
            <label>Descripcion</label>
            <input type="text" class="form-control" disabled
            name="descripcion" value="{{ producto.descripcion }}"
            placeholder="Descripcion">
          </div>

          <div class="form-group col-md-4">
            <label>Costo</label>
            <input type="number" class="form-control {% if form.costo.errors %} is-invalid{%  endif %} " 
            name="costo" value="{{ producto.costo }}"
            placeholder="Costo">
            <div class="invalid-feedback">
                {% for error in form.costo.errors %}{{error}}{% endfor %}
            </div>
          </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-4">
                <label>Precio</label>
                <input type="number" class="form-control {% if form.precio.errors %}is-invalid{% endif %}" 
                name="precio" value="{{ producto.precio }}"
                placeholder="Precio">
                <div class="invalid-feedback">
                    {% for error in form.precio.errors %}{{error}}{% endfor %}
                </div>
              </div>

              <div class="form-group col-md-4">
                <label>Existencia</label>
                <input type="number" readonly class="form-control {% if form.existencia.errors %}is-invalid{% endif %}" 
                name="existencia" value="{{ producto.existencia }}"
                placeholder="Existencia">
                <div class="invalid-feedback">
                    {% for error in form.existencia.errors %}{{error}}{% endfor %}
                </div>
              </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-2">Estado</div>
                <div class="col-sm-10">
                  <div class="form-check">
                    <input class="form-check-input" class="form-check-input "
                     type="checkbox" name="estado" {%if producto.estado %}checked{% endif %}>
                     <div class="invalid-feedback">
                      {% for error in form.estado.errors %}{{ error }}{% endfor %}
                  </div>
                  </div>
                </div>
              </div>
            <button type="submit" class="btn btn-primary">Registrar</button>

      </form>
</div>
    
{% endblock container %}
    
    

templates/productos/new.html
{% extends 'base.html' %}

{% block head_content %}
    <title>Crear nuevo</title>
{% endblock%}





{% block container %}

<div class="container">



    <form method="POST">
        {% csrf_token %}
        <div class="form-row">
        <div class="form-group col-md-4">
            <label>Descripcion</label>
            <input type="text" class="form-control {% if form.descripcion.errors %}is-invalid{% endif %}"
            name="descripcion"
            placeholder="Descripcion">
            <div class="invalid-feedback">
                {% for error in form.descripcion.errors %}{{ error }}{% endfor %}
            </div> 
          </div>
          <div class="form-group col-md-4">
            <label>Costo</label>
            <input type="number" class="form-control {% if form.costo.errors %} is-invalid{%  endif %} " 
            name="costo"
            placeholder="Costo">
            <div class="invalid-feedback">
                {% for error in form.costo.errors %}{{error}}{% endfor %}
            </div>
          </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-4">
                <label>Precio</label>
                <input type="number" class="form-control" 
                name="precio"
                placeholder="Precio">
              </div>
              <div class="form-group col-md-4">
                <label>Existencia</label>
                <input type="number" readonly value="0" class="form-control" 
                name="existencia"
                placeholder="Existencia">
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Registrar</button>

      </form>
    
</div>



{% endblock container %}