api/urls.py
from django.urls import path, include
from .views import ProductoList, ProductoDetalle

urlpatterns = [
    path('v1/productos/',ProductoList.as_view(),name='producto_list'),
    path('v1/productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_detalle'),
]

clientes/urls.py
"""Clientes URLs."""

# Django
from django.urls import path

# Views
from clientes import views

urlpatterns = [

    path(
        route='',
        view=views.ClientsViewDetail.as_view(),
        name='detail'
    ),

    path(
        route='nuevo/',
        view=views.CreateClientsNew.as_view(),
        name='create'
    ),
    path(
        route='editar/<int:pk>',
        view = views.EditClientView.as_view(),
        name='edit'        
    ),
    path(
        route ='eliminar/<int:pk>',
        view = views.DeleteClientView.as_view(),
        name='delete'
    )
]

compras/urls.py
"""Compras URLs."""

# Django
from django.urls import path

# View
# from compras import views

from .views import index, compras, ComprasView, CompraDetDelete

urlpatterns = [

    path(
        route='',
        view=ComprasView.as_view(),
        name='compras_list'
    ),
    path('new/',compras, name="compras_new"),
    path('edit/<int:compra_id>',compras, name="compras_edit"),    
    path('compras/<int:compra_id>/delete/<int:pk>',CompraDetDelete.as_view(), name="compras_del"),

]

ferreteria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views

urlpatterns = [    
    path('admin/', admin.site.urls),
    path('',views.welcome, name="feed"),
    path('compras/', include(('compras.urls', 'compras'), namespace='compras')),
    path('clientes/', include(('clientes.urls', 'clientes'), namespace='clientes')),
    path('productos/', include(('productos.urls', 'productos'), namespace='productos')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('ventas/',include(('ventas.urls','ventas'),namespace='ventas')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Users URLs."""

# Django
from django.urls import path

# View
from users import views


urlpatterns = [
    # Management
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    )


]

ventas/urls.py
from django.urls import path, include

from .views import FacturaView, facturas, ProductoView

from ventas.reportes import imprimir_venta



urlpatterns = [
    path('',FacturaView.as_view(),name='venta_list'),
    path('new/',facturas,name='venta_new'),
    path('buscar-producto/',ProductoView.as_view(), name="venta_producto"),
    path('edit/<int:id>',facturas, name="venta_edit"),
    path('<int:id>/imprimir',imprimir_venta, name="venta_imprimir_one"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}

 <!-- Custom fonts for this template-->
 <link href="{% static  'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
 <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">


  <!-- Custom styles for this page -->
  <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css'%}" rel="stylesheet">

  <!-- jQuery Confirm -->
 <link rel="stylesheet" href="{% static 'vendor/jquery_confirm/jquery-confirm.min.css' %}">

 <!-- XDSoft DateTimePicker -->  
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />  

 <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.css">
 <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/css/select2.min.css" rel="stylesheet" />











    <!-- Bootstrap core JavaScript-->
    <script src="{% static  'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static  'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    
  
    <!-- Core plugin JavaScript-->
    <script src="{% static  'vendor/jquery-easing/jquery.easing.min.js' %}"></script>




    <!--<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <!--<link rel="stylesheet" href="{% static 'css/main.css' %}" />-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <!--
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    -->


    <!-- Page level plugins -->
  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js'%}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

  <script src="{% static 'vendor/jquery_confirm/jquery-confirm.min.js' %}"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>  

  <script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.js"></script>
  <script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table-locale-all.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js"></script>

  <script src="{% static  'js/jquery.chained.min.js' %}"></script>





  
</head>
<body>

    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}

        {% endblock%}


        
        <div class="modal fade" id="popup"></div>

        

        

      
      
        <script>
          $(document).ready(function () {
            jQuery.datetimepicker.setLocale('es');
          });
      </script>

{% block control_modal%}
<script>
  function abrir_modal(url)
  {

    $("#popup").load(url, function(){
      $(this).modal({
        backdrop:'static',
        keyboard: false
      })
      $(this).modal('show');
    });
    return false;
  }

  function cerrar_modal()
  {
    $('#popup').modal('hide');
    return false;
  }

  function mensaje(msg,color='green')
  {
    if (color=="success")
    {
      color="green";
    }
    if (color=="error")
    {
      color="red";
    }


    $.alert({
      title:'',
      theme:'material',
      type:color,
      content:msg
    });
  }

  {% if messages %}
    {% for message in messages %}
      console.log("{{ message.tags }}");
      mensaje("{{ message }}","{{ message.tags }}");
    {% endfor %}
  {% endif %}

</script>
{% endblock%}

        {% block js_page %} {% endblock %}

    </div>

</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
   <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url "feed" %}">
      <img src="{% static "img/ferreteria.jpg" %}" height="55" width="50" class="d-inline-block align-top"/>
      </a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav mr-auto">
            <li class="nav-item">
               <a class="nav-link" href="{% url "clientes:detail" %}">Clientes</a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href="{% url "productos:detail" %}">Producto</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'compras:compras_list' %}">Compras</a>
           </li>


            <li class="nav-item">
               <a class="nav-link" href="{% url 'ventas:venta_list' %}">Ventas</a>
            </li>

         </ul>
         <form class="form-inline my-2 my-lg-0">
            <li class="nav-item nav-icon">
               <a href="{% url "users:logout" %}">
               <i class="fas fa-sign-out-alt"></i>
               </a>
            </li>
         </form>
      </div>
   </div>
</nav>

templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>