api/urls.py
from django.urls import path, include
from .views import ProductoList, ProductoDetalle

urlpatterns = [
    path('v1/productos/',ProductoList.as_view(),name='producto_list'),
    path('v1/productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_detalle'),
]

clientes/urls.py
"""Clientes URLs."""

# Django
from django.urls import path

# Views
from clientes import views

urlpatterns = [

    path(
        route='',
        view=views.ClientsViewDetail.as_view(),
        name='detail'
    ),

    path(
        route='nuevo/',
        view=views.CreateClientsNew.as_view(),
        name='create'
    ),
    path(
        route='editar/<int:pk>',
        view = views.EditClientView.as_view(),
        name='edit'        
    ),
    path(
        route ='eliminar/<int:pk>',
        view = views.DeleteClientView.as_view(),
        name='delete'
    )
]

ferreteria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views

urlpatterns = [    
    path('admin/', admin.site.urls),
    path('',views.welcome, name="feed"),
    path('compras/', include(('compras.urls', 'compras'), namespace='compras')),
    path('clientes/', include(('clientes.urls', 'clientes'), namespace='clientes')),
    path('productos/', include(('productos.urls', 'productos'), namespace='productos')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('ventas/',include(('ventas.urls','ventas'),namespace='ventas')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clientes/models.py
from django.db import models

# Create your models here.

class Clientes(models.Model):
    nombre = models.CharField(max_length=250, blank=False)
    direccion = models.CharField(max_length=350)
    telefono = models.IntegerField()
    nit = models.IntegerField(unique=True, blank=False)
    estado = models.BooleanField(default=True)
    fechaCreacion = models.DateTimeField(auto_now_add=True)
    fechaModificacion = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.nombre
    

clientes/forms.py
from django import forms
from clientes.models import Clientes

class ClientesForm(forms.ModelForm):
    class Meta:
        model = Clientes
        fields = ['nombre','direccion','telefono','nit']

clientes/views.py
from django.shortcuts import render, redirect

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
# Create your views here.

from clientes.forms import ClientesForm

# Models
from clientes.models import Clientes

class CreateClientsNew(LoginRequiredMixin, CreateView):
    """Create a new post."""

    template_name = 'clientes/new.html'
    form_class = ClientesForm
    success_url = reverse_lazy('clientes:detail')



class ClientsViewDetail(LoginRequiredMixin, ListView):
    """Return post detail."""

    template_name = 'clientes/detail.html'
    model = Clientes
    ordering = ('-fechaCreacion',)
    context_object_name = 'clients'


class EditClientView(LoginRequiredMixin,UpdateView):
    template_name = 'clientes/editar.html'
    model = Clientes
    success_url = reverse_lazy('clientes:detail')
    fields = ['direccion','telefono','estado']
    ##fields = "__all__"

class DeleteClientView(DeleteView):
    template_name = 'clientes/confirmacioneliminacion.html'
    model = Clientes    
    success_url = reverse_lazy('clientes:detail')

templates/clientes/confirmacioneliminacion.html
{% extends 'base.html' %}


{% block head_content %}
    <title>Clientes</title>
{% endblock%}

{% block container %}

<br>
<br>


<div class="container">
    <br>
    <br>
    <br>

    <form method="post">{% csrf_token %}
        ¿Estás seguro que deseas borrar el cliente <strong>"{{ object }}"</strong> ?
        <br>
        <input type="submit" value="Confirmar" class="btn btn-success" />
    </form>
    <br>
    
    <a href="{% url "clientes:detail" %}" class="btn btn-info"><i class="fas fa-arrow-alt-circle-left"></i>&nbsp; Regresar</a>              

</div>




{% endblock %}

templates/clientes/detail.html
{% extends "base.html" %}

{% block head_content %}
    <title>Clientes</title>
{% endblock%}

{% block container %}





<div class="container">
    <div class="row">
      <div class="col-12">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Nombre</th>
              <th scope="col">Direccion</th>
              <th scope="col">Telefono</th>
              <th scope="col">Estado</th>
              <th scope="col">Acciones</th>
            </tr>
          </thead>
          <tbody>
            {% for cliente in clients %}  
      

            <tr>  
                <td>{{ cliente.id }}</td>  
                <td>{{ cliente.nombre }}</td>  
                <td>{{ cliente.direccion }}</td>  
                <td>{{ cliente.telefono }}</td>  
                {% csrf_token %}
                <td class="center"><input type="checkbox" disabled name="checkbox"  {%if cliente.estado %}checked{% endif %}/></td>
                
                <td>                                      
                   <a href="{% url "clientes:edit" cliente.id %}" class="btn btn-success"><i class="fas fa-edit"></i></a>
                   <a href="{% url "clientes:delete" cliente.id %}" class="btn btn-danger"><i class="far fa-trash-alt"></i></a>                  
                  </td>
            </tr>  
            {% endfor %}  
          </tbody>
        </table>
        <br>
        <br>
        <a href="{% url "clientes:create" %}" class="btn btn-primary"><i class="fas fa-plus-circle"></i> Agregar nuevo</a>
      </div>
    </div>
  </div>

    

{% endblock %}

templates/clientes/editar.html
{% extends 'base.html' %}

{% block head_content %}
    <title>Editar</title>
{% endblock%}

{% block container %}

<br>
<br>
<div class="container">
    <br>
    <br>
    <br>

      <form method="POST">
        {% csrf_token %}
        <div class="form-group row">
          <label for="inputEmail3" class="col-sm-2 col-form-label">Direccion</label>
          <div class="col-sm-10">
            <input type="text" class="form-control {% if form.direccion.errors %}is-invalid{% endif %}"
            placeholder="Direccion" name="direccion" value="{{ clientes.direccion }}"/>
            <div class="invalid-feedback">
                {% for error in form.direccion.errors %}{{ error }}{% endfor %}
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label for="inputPassword3" class="col-sm-2 col-form-label">Telefono</label>
          <div class="col-sm-10">
            <input type="number" class="form-control {% if form.telefono.errors %}is-invalid{% endif %}"
            laceholder="Telefono"
            name="telefono" placeholder="1234-5678" value="{{ clientes.telefono }}" />
            <div class="invalid-feedback">
                {% for error in form.telefono.errors %}{{ error }}{% endfor %}
            </div>
          </div>
        </div>
   
        <div class="form-group row">
          <div class="col-sm-2">Estado</div>
          <div class="col-sm-10">
            <div class="form-check">
              <input class="form-check-input" class="form-check-input "
               type="checkbox" name="estado" {%if clientes.estado %}checked{% endif %}>
               <div class="invalid-feedback">
                {% for error in form.estado.errors %}{{ error }}{% endfor %}
            </div>
            </div>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Actualizar</button>
          </div>
        </div>

        
        
        <div class="form-group row">
            <div class="col-sm-10">
                <a href="{% url "clientes:detail" %}" class="btn btn-info"><i class="fas fa-arrow-alt-circle-left"></i>&nbsp; Regresar</a>              
            </div>
          </div>
      </form>




</div>
{% endblock container %}

templates/clientes/new.html
{% extends 'base.html' %}

{% block head_content %}
    <title>Crear nuevo</title>
{% endblock%}



{% block container %}

<br>
<Br>
<div class="container">

    <form  method="POST">
     
        {% csrf_token %}
        <div class="form-row">

          <div class="form-group col-md-4">              
            <label for="inputEmail4">Nombre</label>
            <input type="text" class="form-control {% if form.nombre.errors %}is-invalid{% endif %}"
             placeholder="Nombre"
             name="nombre">
            <div class="invalid-feedback">
                {% for error in form.nombre.errors %}{{ error }}{% endfor %}
            </div>            
          </div>

          <div class="form-group col-md-4">              
            <label for="inputPassword4">Telefono</label>
            <input type="number" class="form-control {% if form.telefono.errors %}is-invalid{% endif %}"
            laceholder="Telefono"
            name="telefono" placeholder="1234-5678">
            <div class="invalid-feedback">
                {% for error in form.telefono.errors %}{{ error }}{% endfor %}
            </div>
          </div>

          <div class="form-group col-md-4">                        
            <label for="inputPassword4">NIT</label>
            <input type="number" class="form-control {% if form.nit.errors %}is-invalid{% endif %}"
            placeholder="NIT"
            name="nit">
            <div class="invalid-feedback">
                {% for error in form.nit.errors %}{{ error }}{% endfor %}
            </div>
          </div>
        </div>

        <div class="form-group">            
          <label for="inputAddress">Direccion</label>
          <input type="text" class="form-control {% if form.direccion.errors %}is-invalid{% endif %}"
          name="direccion"
          placeholder="Direccion">
            <div class="invalid-feedback">
                {% for error in form.direccion.errors %}{{ error }}{% endfor %}
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Registrar</button>
      </form>
      <br>

      <a href="{% url "clientes:detail" %}" class="btn btn-info"><i class="fas fa-arrow-alt-circle-left"></i>&nbsp; Regresar</a>              
</div>
<br>




    
{% endblock container %}